personal_blog/books/forms.py
"""Module containing form classes for the books blueprint.

---

Classes
-------
BookForm: child of FlaskForm
    the form used to add/update books
"""

from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired


class BookForm(FlaskForm):
    """The class used to build the book form.

    Inherit from FlaskForm base class.
    Create class variables, which are used as form fields and buttons.

    ---

    Class variables
    ---------------
    title: StringField
        the book title field
    authors: StringField
        the book authors field
    edition: StringField
        the book edition field
    link: StringField
        the book link field
    description: TextAreaField
        the book description/evaluation field
    submit: SubmitField
        the submit button
    """

    title = StringField('Title', validators=[DataRequired()])
    authors = StringField('Authors', validators=[DataRequired()])
    edition = StringField('Edition', validators=[DataRequired()])
    link = StringField('Link')
    description = TextAreaField('Description', validators=[DataRequired()])
    submit = SubmitField('Add')

personal_blog/posts/forms.py
"""Module containing form classes for the posts blueprint.

---

Classes
-------
PostForm: child of FlaskForm
    the form used for creating/editing posts
CommentForm: child of FlaskForm
    the form used for creating comments
"""

from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from flask_ckeditor import CKEditorField
from wtforms.validators import DataRequired


class PostForm(FlaskForm):
    """The class used to build the post form.

    Inherit from FlaskForm base class.
    Create class variables, which are used as form fields and buttons.

    ---

    Class variables
    ---------------
    title: StringField
        the post title field, mandatory
    tags: StringField
        the post's tags, mandatory
    content: CKEditorField
        the post contents, mandatory
    submit: SubmitField
        the form submit button
    """

    title = StringField('Title', validators=[DataRequired()])
    tags = StringField('Tags', validators=[DataRequired()])
    content = CKEditorField('Content', validators=[DataRequired()])
    submit = SubmitField('Post')


class CommentForm(FlaskForm):
    """The class used to build the comment form.

    Inherit from FlaskForm base class.
    Create class variables, which are used as form fields and buttons.

    ---

    Class variables
    ---------------
    content: TextAreaField
        the comment contents, mandatory
    submit: SubmitField
        the form submit button
    """
    content = TextAreaField('Comment', validators=[DataRequired()])
    submit = SubmitField('Post')

personal_blog/books/routes.py
"""Module containing route functions for the books blueprint.

---

Functions
---------
add_book(): return http response
    the route for adding books
all_books(): return http response
    the route for displaying all books
book(book_id): return http response
    the route for displaying a single book
update_book(book_id): return http response
    the route for updating a book
delete_book(book_id): return http response
    the route for deleting a book
"""

from flask import Blueprint, render_template, url_for, flash, redirect, abort,\
        request
from flask_login import current_user, login_required

from personal_blog import db
from personal_blog.models import Book
from personal_blog.books.forms import BookForm

books = Blueprint('books', __name__)


@books.route("/book/new", methods=['GET', 'POST'])
@login_required
def add_book():
    """The route function for adding books.

    If the user isn't admin, don't do anything.
    If the form validates, add book to db.
    Flash the message, and redirect to all books.
    Else, just load the form (render the template).

    ---

    Returns
    -------
    http response
    """

    if not current_user.is_admin:  # only the admin adds books
        abort(403)
    form = BookForm()
    if form.validate_on_submit():
        book = Book(title=form.title.data, authors=form.authors.data,
                    link=form.link.data, edition=form.edition.data,
                    description=form.description.data)
        db.session.add(book)
        db.session.commit()
        flash('Book has been added!', 'success')
        return redirect(url_for('books.all_books'))
    return render_template('books/add_book.html', title='New Book',
                           form=form, legend='Add Book', hide_sidebar=True)


@books.route("/all_books")
def all_books():
    """The route function for displaying all books.

    Get all the records from the books table.
    Render the template.

    ---

    Returns
    -------
    http response
    """

    books = Book.query.all()
    return render_template('books/all_books.html', books=books)


@books.route("/book/<int:book_id>")
def book(book_id):
    """The route for displaying a single book.

    Query the books table for the record with that book id.
    Render the template.

    ----

    Parameters
    ----------
    book_id: int
        the id for the book to be displayed

    Returns
    -------
    http response
    """

    book = Book.query.get_or_404(book_id)
    return render_template('books/book.html', title=book.title, book=book)


@books.route("/book/<int:book_id>/update", methods=['GET', 'POST'])
@login_required
def update_book(book_id):
    """The route for updating a book.

    Get the book with that id, or return a 404.
    If the user isn't admin, don't do anything.
    If the form validates, apply changes to db.
    Flash the message, and redirect to that book's route.
    Else, render the template with the loaded record.

    ---

    Parameters
    ----------
    book_id: int
        the id of the book to be updated

    Returns
    -------
    http response
    """

    book = Book.query.get_or_404(book_id)
    if not current_user.is_admin:  # only the admin can update books
        abort(403)  # forbidden route
    form = BookForm()
    form.submit.label.text = 'Update'
    if form.validate_on_submit():
        book.title = form.title.data
        book.authors = form.authors.data
        book.edition = form.edition.data
        if form.link.data:
            book.link = form.link.data
        book.description = form.description.data
        db.session.commit()
        flash('Book has been updated!', 'success')
        return redirect(url_for('books.book', book_id=book.id))
    elif request.method == 'GET':
        form.title.data = book.title
        form.authors.data = book.authors
        form.edition.data = book.edition
        form.link.data = book.link
        form.description.data = book.description
    return render_template('books/add_book.html', title='Update Book',
                           form=form, legend='Update Book', hide_sidebar=True)


@books.route("/book/<int:book_id>/delete", methods=['POST'])
@login_required
def delete_book(book_id):
    """The route for deleting a book.

    Get the book with that id, or return a 404.
    If the user isn't admin, don't do anything.
    Delete the book from the db.
    Flash the message, and redirect to all books.

    ---

    Parameters
    ----------
    book_id: int
        the id of the book to be deleted

    Returns
    -------
    http response
    """

    book = Book.query.get_or_404(book_id)
    if not current_user.is_admin:
        abort(403)  # forbidden route
    db.session.delete(book)
    db.session.commit()
    flash('Book has been deleted!', 'success')
    return redirect(url_for('books.all_books'))

personal_blog/posts/routes.py
"""Module containing the route functions for the posts blueprint.

---

Functions
---------
new_post(): return http response
    the route for creating a new post
post(post_id): return http response
    the route for displaying a post with that id
update_post(post_id): return http response
    the route for updating a post with that id
delete_post(post_id): return http response
    the route for deleting a post with that id
all_posts(): return http response
    the route for displaying all posts
comment(post_id): return http response
    the route for adding a comment to that post
posts_by_tag(tag_content): return http response
    the route for displaying all posts with that tag
tags(): return http response
    the route for displaying all posts, grouped by tag
uploaded_files(filename): return http response, file url
    the route for getting the static file with that filename
upload(): return http response, file url
    the route for uploading a file (post image)
"""

import os
from secrets import token_hex

from flask import Blueprint, render_template, url_for, flash, redirect,\
    request, abort, send_from_directory, current_app
from flask_login import current_user, login_required
from flask_ckeditor import upload_fail, upload_success

from personal_blog import db
from personal_blog.models import Post, Tag, Comment
from personal_blog.posts.forms import PostForm, CommentForm
from personal_blog.posts.utilities import delete_post_images

posts = Blueprint('posts', __name__)


@posts.route("/post/new", methods=['GET', 'POST'])
@login_required
def new_post():
    """The route for creating a new post.

    If the current user isn't admin, early return code 403.
    If the form validates, create post and tag records.
    Flash the message, and redirect home.
    If it doesn't validate, simply render the template.

    ---

    Returns
    -------
    http response
    """

    if not current_user.is_admin:  # only the admin creates posts
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        post = Post(title=form.title.data, content=form.content.data,
                    author=current_user)
        db.session.add(post)
        # add tags
        tags = form.tags.data
        tags = set(tags.split(' '))
        parent_post = Post.query.order_by(Post.date_posted.desc()).first()
        for tag_name in tags:
            tag = Tag(content=tag_name, parent_post=parent_post)
            db.session.add(tag)
        # commit to db
        db.session.commit()
        flash('Post has been created!', 'success')
        return redirect(url_for('main.home'))
    return render_template('posts/create_post.html', title='New Post',
                           form=form, legend='Create Post', hide_sidebar=True)


@posts.route("/post/<int:post_id>")
def post(post_id):
    """The route function for displaying a post with that id.

    Get the post with that id, or return a 404.
    Get the comments for the post, ordered by date posted.
    Get the tags for the post. Render the template.

    ---

    Parameters
    ----------
    post_id: int
        the id of the post to be displayed

    Returns
    -------
    http response
    """

    post = Post.query.get_or_404(post_id)
    comments = Comment.query.filter_by(post_id=post_id).order_by(
            Comment.date_posted.asc())
    tags = Tag.query.filter_by(post_id=post_id)
    return render_template('posts/post.html', title=post.title, post=post,
                           comments=comments, tags=tags)


@posts.route("/post/<int:post_id>/update", methods=['GET', 'POST'])
@login_required
def update_post(post_id):
    """The route function for updating the post with that id.

    Get the post with that id, or return a 404.
    If the current user isn't the post author, return a 403.
    If the form validates, update the post record, delete the
    old tag records and create new ones, and then commit to db.
    Flash the message, and redirect to that post's route.
    If the form doesn't validate, or the request is GET,
    simply render the template.

    ---

    Parameters
    ----------
    post_id: int
        the id of the post to be updated

    Returns
    -------
    http response
    """

    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)  # forbidden route
    form = PostForm()
    form.submit.label.text = 'Update'
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        old_tags = Tag.query.filter_by(post_id=post_id)
        for tag in old_tags:
            db.session.delete(tag)
        new_tags = form.tags.data
        new_tags = set(new_tags.split(' '))
        for i in new_tags:
            tag = Tag(content=i, parent_post=post)
            db.session.add(tag)
        db.session.commit()
        flash('Your post has been updated!', 'success')
        return redirect(url_for('posts.post', post_id=post.id))
    elif request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.content
        tags = [tag.content for tag in post.tags]
        form.tags.data = ' '.join(tags)
    return render_template('posts/create_post.html', title='Update Post',
                           form=form, legend='Update Post', hide_sidebar=True)


@posts.route("/post/<int:post_id>/delete", methods=['POST'])
@login_required
def delete_post(post_id):
    """The route function for deleting the post with that id.

    Get the post with that id, or return a 404.
    If the current user isn't the post author, return a 403.
    Delete the post record, and commit to db.
    Delete the image files associated with that post.
    Flash the message, and redirect home.

    ---

    Parameters
    ----------
    post_id: int
        the id of the post to be deleted

    Returns
    -------
    http response
    """

    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)  # forbidden route
    content = post.content
    db.session.delete(post)
    db.session.commit()
    delete_post_images(content, current_app.root_path)
    flash('Your post has been deleted!', 'success')
    return redirect(url_for('main.home'))


@posts.route("/all_posts")
def all_posts():
    """The route function for displaying all posts.

    Get current page from the request object.
    Get all posts, ordered by date, and paginated.
    Render the template for the current page.

    ---

    Returns
    -------
    http response
    """

    page = request.args.get('page', 1, type=int)
    posts = Post.query.order_by(Post.date_posted.desc()).paginate(
        page=page, per_page=current_app.config['PER_PAGE_GLOBAL'])
    return render_template('posts/all_posts.html', posts=posts)


@posts.route("/post/<int:post_id>/comment", methods=['GET', 'POST'])
@login_required
def comment(post_id):
    """The route function for adding a comment to that post.

    Get the post with that id, or return a 404.
    If the form validates, create a comment record and commit it.
    Flash the message, and redirect to the post.
    If it doesn't validate, simply render the template.

    ---

    Parameters
    ----------
    post_id: int
        the id of the post to be commented on

    Returns
    -------
    http response
    """

    post = Post.query.get_or_404(post_id)
    form = CommentForm()
    if form.validate_on_submit():
        comment = Comment(content=form.content.data, user_id=current_user.id,
                          post_id=post.id)
        db.session.add(comment)
        db.session.commit()
        flash('Comment has been posted!', 'success')
        return redirect(url_for('posts.post', post_id=post.id))
    return render_template('posts/comment.html', title='Comment', form=form,
                           post=post, hide_sidebar=True)


@posts.route("/all_posts/<string:tag_content>")
def posts_by_tag(tag_content):
    """The route function for displaying all posts with that tag.

    Collect all the tag records with that tag content.
    Get the corresponding post id for each tag record collected.
    Get the current page from the request object.
    Get all the posts with those post ids, ordered by date
    posted, and paginated.
    Render the template.

    ---

    Parameters
    ----------
    tag_content: str
        the tag whole posts are to be displayed (i.e. 'django')

    Returns
    -------
    http response
    """

    tags = Tag.query.filter_by(content=tag_content).all()
    post_ids = [tag.post_id for tag in tags]
    page = request.args.get('page', 1, type=int)
    posts = db.session.query(Post).filter(Post.id.in_(post_ids)).order_by(
            Post.date_posted.desc()).paginate(
                page=page, per_page=current_app.config['PER_PAGE_GLOBAL'])
    return render_template('posts/posts_by_tag.html', posts=posts,
                           tag=tag_content)


@posts.route("/tags")
def tags():
    """The route function for displaying all posts, grouped by tag.

    Get all distinct tags. Render the template.

    ---

    Returns
    -------
    http response
    """

    tags = db.session.query(Tag.content.distinct().label("content")).all()
    return render_template('posts/tags.html', Tag=Tag, Post=Post, db=db,
                           tags=tags)


@posts.route('/files/<string:filename>')
def uploaded_files(filename):
    """The route function used by Ckeditor for getting uploaded files.

    Get the app path. Pass it on, along with the name
    of the requested file, to send_from_directory().
    Return the output of send_from_directory().

    ---

    Parameters
    ----------
    filename: str
        the name of the file to be retrieved

    Returns
    -------
    http response, filename url
    """

    path = current_app.config['UPLOADED_PATH']
    return send_from_directory(path, filename)


@posts.route('/upload', methods=['POST'])
def upload():

personal_blog/templates/about.html
{% extends "layout.html" %}
{% block content %}
<article class="content-section">
    <p>Personal blog site built with Python, Flask, HTML5 and Boostrap</p>
    <p>Coded by Julian Hysi, with love</p>
    <p>To get in touch with me, see the Contact section on the sidebar</p>
    <p>All of the source code for this website is available <a href="https://github.com/JulianHysi/personal-blog"><b>here</b></a></p>
    <p>Feel free to contribute to it</p>
    <p><i><b>Under construction</b></i></p>
</article>
{% endblock content %}

personal_blog/templates/account.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        
        <div class="media">
            <img class="rounded-circle account-img" src="{{ profile_pic_path }}">
            <div class="media-body">
                <h2 class="account-heading">{{ current_user.username }}</h2>
                <p class="text-secondary">{{ current_user.email }}</p>
            </div>
        </div>

        <form method="POST" action="" enctype="multipart/form-data">
            {{ form.hidden_tag() }} <!-- CSRF token-->

            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Profile Info</legend>

                <div class="form-group">
                    {{ form.username.label(class="form-control-label") }}

                    {% if form.username.errors %}
                        {{ form.username(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.username(class="form-control form-control-lg") }}
                    {% endif %}
                </div>

                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}

                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>

                <div class="form-group">
                    {{ form.profile_pic.label() }}
                    {{ form.profile_pic(class="form-control-file") }}
                    {% if form.profile_pic.errors %}
                        {% for error in form.profile_pic.errors %}
                            <span class="text-danger">{{ error }}</span></br>
                        {% endfor %}
                    {% endif %}
                </div>

            </fieldset>

            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
                <button class="btn btn-warning">
                    <a href="{{ url_for('main.home') }}">Cancel</a>
                </button>
            </div>

            <div class="form-group">
                <hr>
                <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deactivateModal">
                    Deactivate account
                </button>
            </div>

        </form>

    </div>

<!-- Modal -->
<div class="modal fade" id="deactivateModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">

        <div class="modal-header">
          <h5 class="modal-title" id="deleteModalLabel">Deactivate account ?</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>

        <div class="modal-body">
          <p>Are you sure you want to deactivate your account ?</p>
          <p>This action is not reversible. 
          All your profile info, posts and comments will be permanently deleted.</p>
        </div>

        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
          <form action="{{ url_for('users.deactivate_account') }}" method="POST">
            <input class="btn btn-danger" type="submit" value="Deactivate">
          </form>
        </div>

      </div>
    </div>
  </div>

{% endblock content %}

personal_blog/templates/all_books.html
{% extends "layout.html" %}
{% block content %}

    <h3 class="mb-3">Books I've read and recommend</h3>
    <p class="text-muted mb-3">Click the title to see my notes on the book</p>

    {% for book in books %}
    <article class="media content-section">
        <div class="media-body">
            <h2><a class="article-title" href="{{ url_for('books.book', book_id=book.id) }}">{{ book.title }}</a></h2>
            <p>{{ book.authors }}</p>
            <p>{{ book.edition }}</p>
            {% if book.link %}
                <p>{{ book.link }}</p>
            {% endif %}
        </div>
    </article>
    {% endfor %}

{% endblock content %}

personal_blog/templates/all_posts.html
{% extends "layout.html" %}
{% block content %}

    {% if not tag %}
        <h3 class="mb-3">All posts, in chronological order :</h3>
    {% else %}
        <h3 class="mb-3">All #{{tag}} posts, in chronological order :</h3>
    {% endif %}

    {% for post in posts %}
    <article class="media content-section">
        <a href="{{ url_for('posts.all_posts') }}">
            <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + post.author.profile_pic) }}">
        </a>
        <div class="media-body">
            <div class="article-metadata">
                <a class="mr-2" href="{{ url_for('posts.all_posts') }}">{{ post.author.username }}</a>
                <small class="text-muted right"> {{ post.date_posted.strftime('%d-%m-%Y') }} </small>
            </div> <br>
            <h2><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
        </div>
    </article>
    {% endfor %}

{% endblock content %}

personal_blog/templates/book.html
{% extends "layout.html" %}
{% block content %}

<article class="media content-section">
    <div class="media-body">

        {% if current_user.is_admin %}
            <div class="article-metadata">
                <div class="right"> 
                    <a class="btn btn-success btn-sm" href="{{ url_for('books.update_book', book_id=book.id) }}">Update</a>
                    <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal">
                        Delete
                    </button>
                </div>
                <br><br>
            </div>
        {% endif %}

        <h2 class="article-title mt-2">{{ book.title }}</h2>
        <p>{{ book.authors }}</p>
        <p>{{ book.edition }}</p>
        {% if book.link %}
            <p>{{ book.link }}</p>
        {% endif %}
        <p class="article-content">{{ book.description }}</p>

    </div>
</article>

<!-- Delete Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="deleteModalLabel">Delete Book ?</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
          <form action="{{ url_for('books.delete_book', book_id=book.id) }}" method="POST">
            <input class="btn btn-danger" type="submit" value="Delete">
          </form>
        </div>
      </div>
    </div>
</div>  

{% endblock content %}

personal_blog/templates/home.html
{% extends "layout.html" %}
{% block content %}
    {% for post in posts.items %}
    <article class="media content-section">
        <a href="{{ url_for('posts.all_posts') }}">
            <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + post.author.profile_pic) }}">
        </a>
        <div class="media-body">
            <div class="article-metadata">
                <a class="mr-2" href="{{ url_for('posts.all_posts') }}">{{ post.author.username }}</a>
                <small class="text-muted right"> {{ post.date_posted.strftime('%d-%m-%Y') }} </small>
            </div> <br>
            <h2><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
        </div>
    </article>
    {% endfor %}
    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
        {% if page_num %}
            {% if posts.page == page_num %}
                <a class="btn btn-info mb-4" href="{{ url_for('main.home', page=page_num) }}">{{ page_num}}</a>
            {% else %}
                <a class="btn btn-outline-info mb-4" href="{{ url_for('main.home', page=page_num) }}">{{ page_num}}</a>
            {% endif %}
        {% else %}    
            ...
        {% endif %}
    {% endfor %}
{% endblock content %}

personal_blog/templates/post.html
{% extends "layout.html" %}
{% block content %}
<article class="media content-section">
    <a href="{{ url_for('posts.all_posts') }}">
      <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + post.author.profile_pic) }}">
    </a>
    <div class="media-body">
        <div class="article-metadata">
            <a class="mr-2" href="{{ url_for('posts.all_posts') }}">{{ post.author.username }}</a>
            <small class="text-muted right"> {{ post.date_posted.strftime('%d-%m-%Y') }} </small>
            {% if post.author == current_user %}
            <br>
            <div class="right"> 
                <a class="btn btn-success btn-sm mt-1 mb-1" href="{{ url_for('posts.update_post', post_id=post.id) }}">Update</a>
                <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal">Delete</button>
            </div>
            <br><br>
            {% endif %}
        </div> <br>
        <p class="right">
            {% for tag in tags %}
            <a href="{{ url_for('posts.posts_by_tag', tag_content=tag.content) }}">#{{ tag.content }}</a>
            {% endfor %}
          </p>
        <h2 class="article-title">{{ post.title }}</h2> <br>
        <p class="article-content">{{ post.content | safe }}</p> <!-- '| safe' marks the text as safe to render html -->
        <br>
        <a class="btn btn-warning ml-2 right" href="https://www.facebook.com/sharer/sharer.php?u=example.org"
            target="_blank">Share on Facebook</a>
        <a class="btn btn-warning right" href="https://twitter.com/share?url=#">Share on Twitter</a>
        <a class="btn btn-info" href="{{ url_for('posts.comment', post_id=post.id) }}">Comment</a>
    </div>
</article>

{% if comments  %}
  <div id="comment-section">
    <h4>Comments :</h4>
  </div>
  <div>
    {% for comment in comments %}
      <article id="comment" class="media content-section">
        <a>
          <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + post.author.profile_pic) }}">
        </a>
        <div class="media-body">
          <div class="article-metadata">
              <a id="comment-author">{{ comment.author.username }}</a>
              <small class="text-muted right"> {{ comment.date_posted.strftime('%d-%m-%Y') }} </small>
          </div> <br>
          <p class="article-content">{{ comment.content }}</p>
          <br>
        </div>
      </article>
      <br>
    {% endfor %}
  </div>
  <br>
{% endif %}

<!-- Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="deleteModalLabel">Delete Post ?</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
          <form action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="POST">
            <input class="btn btn-danger" type="submit" value="Delete">
          </form>
        </div>
      </div>
    </div>
</div>  

{% endblock content %}

personal_blog/templates/tags.html
{% extends "layout.html" %}
{% block content %}
    <h3 class="mb-5">All posts groupped by tags :</h3>

    {% for tag in tags %}
    <article class="content-section">
        <div>
            <h3>
                <a class="article-title" href="{{ url_for('posts.posts_by_tag', tag_content=tag.content) }}">#{{ tag.content }}</a>
                <small id="tag-count">({{ Tag.query.filter_by(content=tag.content).count() }} posts)</small>
            </h3>
            <br>
            <div>
                <ul>
                    {% for post in db.session.query(Post).join(Tag).filter_by(content=tag.content).order_by(Post.date_posted.desc()).all() %}
                        <li>- <a href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></li><br>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </article>
    {% endfor %}
{% endblock content %}