personal_blog/users/forms.py
"""Module containing form classes for the users bluepring.

---

Classes
-------
RegistrationForm: child of FlaskForm
    the form used for registering new users
LoginForm: child of FlaskForm
    the form used for loging users in
UpdateAccountForm: child of FlaskForm
    the form used for updating a user profile
RequestResetForm: child of FlaskForm
    the form used for requesting a password reset
ResetPasswordForm: child of FlaskForm
    the form used for resetting the user password
"""

from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileAllowed
from wtforms import StringField, PasswordField, SubmitField, BooleanField
from wtforms.validators import DataRequired, Length, Email, EqualTo,\
    ValidationError
from flask_login import current_user
from personal_blog.models import User


class RegistrationForm(FlaskForm):
    """The class used to build the user registration form.

    Inherit from FlaskForm base class.
    Create class variables, which are used as form fields and buttons.

    ---

    Class variables
    ---------------
    username: StringField
        the user username field, mandatory
    email: StringField
        the user email field, mandatory
    password: PasswordField
        the user password field, mandatory
    confirm_password: PasswordField
        the user password confirm field, mandatory
    submit: SubmitField
        the form submit button

    Methods
    -------
    validate_username(self, username): return None
        raise ValidationError if the username already exists
    validate_email(self, email): return None
        raise ValidationError if the email already exists
    """

    username = StringField('Username', validators=[DataRequired(),
                           Length(min=5, max=20)])
    email = StringField('Email', validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired(),
                             Length(min=5)])
    confirm_password = PasswordField(' Confirm Password',
                                     validators=[DataRequired(),
                                                 EqualTo('password')])
    submit = SubmitField('Register')

    def validate_username(self, username):
        """Raise ValidationError if username is already registered.

        ---

        Parameters
        ----------
        username: str
            the username of the current user being created
        """

        user = User.query.filter_by(username=username.data).first()
        if user:
            raise ValidationError('Username is already taken!')

    def validate_email(self, email):
        """Raise ValidationError if email is already registered.

        ---

        Parameters
        ----------
        email: str
            the email of the current user being created
        """

        user = User.query.filter_by(email=email.data).first()
        if user:
            raise ValidationError('Email is already taken!')


class LoginForm(FlaskForm):
    """The class used to build the login form.

    Inherit from FlaskForm base class.
    Create class variables, which are used as form fields and buttons.

    ---

    Class variables
    ---------------
    email: StringField
        the user email field, mandatory
    password: PasswordField
        the user password field, mandatory
    remember: BooleanField
        the remember me field
    submit: SubmitField
        the form submit button
    """

    email = StringField('Email', validators=[DataRequired(), Email()])
    password = PasswordField('Password',
                             validators=[DataRequired(), Length(min=5)])
    remember = BooleanField('Remember Me')
    submit = SubmitField('Log In')


class UpdateAccountForm(FlaskForm):
    """The class used for building the user update account form.

    Inherit from FlaskForm base class.
    Create class variables, which are used as form fields and buttons.

    ---

    Class variables
    ---------------
    username: StringField
        the user username field, mandatory
    email: StringField
        the user email field, mandatory
    profile_pic: FileField
        the user profile picture file
    submit: SubmitField
        the form submit button

    Methods
    -------
    validate_username(self, username): return None
        raise ValidationError if username already exists
    validate_email(self, username): return None
        raise ValidationError if emaul already exists
    """

    username = StringField('Username',
                           validators=[DataRequired(), Length(min=5, max=20)])
    email = StringField('Email', validators=[DataRequired(), Email()])
    profile_pic = FileField('Update profile picture',
                            validators=[FileAllowed(['jpeg', 'jpg', 'png'])])
    submit = SubmitField('Update')

    def validate_username(self, username):
        """Raise ValidationError if username already exists.

        If there's already a user with that username, and that user
        is not the current user, raise a ValidationError.

        ---

        Parameters
        ----------
        username: str
            the user username to be validated
        """

        user = User.query.filter_by(username=username.data).first()
        if user and user.username != current_user.username:
            raise ValidationError('Username is already taken!')

    def validate_email(self, email):
        """Raise ValidationError if email already exists.

        If there's already a user with that email, and that user
        is not the current user, raise a ValidationError.

        ---

        Parameters
        ----------
        email: str
            the user email to be validated
        """

        user = User.query.filter_by(email=email.data).first()
        if user and user.email != current_user.email:
            raise ValidationError('Email is already taken!')


class RequestResetForm(FlaskForm):
    """The class used to build the request password reset form.

    Inherit from FlaskForm base class.
    Create class variables, which are used as form fields and buttons.

    ---

    Class variables
    ---------------
    email: StringField
        the email of the account requesting a password reset
    submit: SubmitField
        the form submit button
    """

    email = StringField('Email', validators=[DataRequired(), Email()])
    submit = SubmitField('Request password reset')


class ResetPasswordForm(FlaskForm):
    """The class used to build the user reset password form.

    Inherit from FlaskForm base class.
    Create class variables, which are used as form fields and buttons.

    ---

    Class variables
    ---------------
    password: PasswordField
        the new password
    confirm_password: PasswordField
        the new password, confirmed
    submit: SubmitField
        the form submit button
    """

    password = PasswordField('Password',
                             validators=[DataRequired(), Length(min=5)])
    confirm_password = PasswordField('Confirm Password',
                                     validators=[DataRequired(),
                                                 EqualTo('password')])
    submit = SubmitField('Reset password')

personal_blog/users/routes.py
"""Module containing the route functions for the users blueprint.

---

Functions
---------
register(): return http response
    the route for registering a new user
login(): return http response
    the route for logging a user in
logout(): return http response
    the route for loggin a user out
account(): return http response
    the route for displaying a user account
deactivate_account(): return http response
    the route for deactivating a user account
reset_request(): return http response
   the route for requesting a password reset
reset_token(): return http response
    the route for resetting the password
"""

from flask import Blueprint, render_template, url_for, flash, redirect,\
        request, current_app, session
from flask_login import login_user, current_user, logout_user, login_required

from personal_blog import db, bcrypt
from personal_blog.models import User
from personal_blog.users.forms import RegistrationForm, LoginForm,\
    UpdateAccountForm, RequestResetForm, ResetPasswordForm
from personal_blog.users.utilities import save_profile_picture,\
        delete_old_profile_picture, send_reset_email

users = Blueprint('users', __name__)


@users.route("/register", methods=['GET', 'POST'])
def register():
    """The route for registering a new user.

    If the current user is already authenticated, redirect home.
    If the form validates, create the new user and commit to db.
    Hash the passsword first. Set the is_admin property to yes
    if no other user has it on (there can be only 1 admin).
    Flash the message, and redirect to the login route.
    If the form doesn't validate, simply render the template.

    ---

    Returns
    -------
    http response
    """

    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        passwd = form.password.data
        hashed_passwd = bcrypt.generate_password_hash(passwd).decode('utf-8')
        user = User()
        user.username = form.username.data
        user.email = form.email.data
        user.password = hashed_passwd
        user.is_admin = 0 if User.query.filter_by(is_admin=1).first() else 1
        db.session.add(user)
        db.session.commit()
        flash(f'Account {form.username.data} has been registered. '
              'You can proceed with the login.', 'success')
        return redirect(url_for('users.login'))
    return render_template('users/register.html', title='Register', form=form,
                           hide_sidebar=True)


@users.route("/login", methods=['GET', 'POST'])
def login():
    """The route for logging a user in.

    If the user is already authenticated, redirect home.
    If the form validates, and the credentials match a
    user in the db, log the user in. Set the session to
    permanent, in order for timeouts to work.
    Get the next page url parameter from the request object.
    If there is a next page, redirect to it. Else, to home.
    If the form validates, but credentials dont match,
    flash a warning message.
    If he form doesn't validate, simply render the template.

    ---

    Returns
    -------
    http response
    """

    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password,
                                               form.password.data):
            session.permanent = True
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')  # url parameter
            if next_page:
                return redirect(next_page)
            else:
                return redirect(url_for('main.home'))
        else:
            flash('Please enter the right credentials..', 'danger')
    return render_template('users/login.html', title='Log In', form=form,
                           hide_sidebar=True)


@users.route("/logout")
def logout():
    """The route for logging a user out.

    Log the user out, and redirect home.

    ---

    Returns
    -------
    http response
    """

    logout_user()
    return redirect(url_for('main.home'))


@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    """The route for displaying/editing a user account profile.

    If the form validates, update the current user.
    If there was an update of profile picture, delete the old
    one from the filesystem, and store the new one.
    Commit to db, flash the message, and redirect to this route.
    If the form doesn't validate and request is GET, simply
    preload the account form with data, and render the template.

    ---

    Returns
    -------
    http response
    """

    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.profile_pic.data:
            delete_old_profile_picture(current_user.profile_pic,
                                       current_app.root_path)
            profile_pic_file = save_profile_picture(form.profile_pic.data,
                                                    current_app.root_path)
            current_user.profile_pic = profile_pic_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Profile has been updated', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email

    profile_pic_path = url_for(
        'static', filename='profile_pics/' + current_user.profile_pic)

    return render_template('users/account.html', title='Profile',
                           profile_pic_path=profile_pic_path, form=form)


@users.route("/account/deactivate", methods=['POST'])
@login_required
def deactivate_account():
    """The route for deactivating a user account.

    If the current user is admin, do not allow the deactivation.
    Flash the message, and redirect to that user's account.
    Else, delete the current user, commit to db, delete their
    profile picture from the filesystem, flash the message, and
    redirect to the logout route.

    ---

    Returns
    -------
    http response
    """

    if current_user.is_admin:
        flash('Admin account cannot be deactivated', 'danger')
        return redirect(url_for('users.account'))
    filename = current_user.profile_pic
    db.session.delete(current_user)
    db.session.commit()
    delete_old_profile_picture(filename, root_path=current_app.root_path)
    flash('Your account has been deactivated!', 'success')
    return redirect(url_for('users.logout'))


@users.route('/reset_password', methods=['GET', 'POST'])
def reset_request():
    """The route for requesting a password reset.

    If the current user is authenticated, redirect home.
    If the form validates, get the user with that email.
    If the user exists, send the reset email. But flash
    the message anyway as a security best practice, and
    redirect to the login route.
    If the form doesn't validate, simply render the template.

    ---

    Returns
    -------
    http response
    """

    if current_user.is_authenticated:
        return redirect(url_for('users.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user:
            send_reset_email(user)
        flash('An email has been sent with instructions to reset '
              'your password', 'info')
        return redirect(url_for('users.login'))
    return render_template('users/reset_request.html', title='Reset Password',
                           form=form)


@users.route('/reset_password/<string:token>', methods=['GET', 'POST'])
def reset_token(token):
    """The route for resetting the password.

    If the current user is authenticated, redirect home.
    If the token isn't valid, flash the message and
    redirect to the reset_request route.
    If the form validates, get the new password, hash its
    value and update the user with it.
    Commit to db, flash the message and redirect to login.
    If the form doesn't validate, simply render the template.

    ---

    Returns
    -------
    http response
    """

    if current_user.is_authenticated:
        return redirect(url_for('users.home'))
    user = User.verify_reset_token(token)
    if not user:
        flash('Invalid/expired token', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        passwd = form.password.data
        hashed_passwd = bcrypt.generate_password_hash(passwd).decode('utf-8')
        user.password = hashed_passwd
        db.session.commit()
        flash('Your password has been updated. '
              'You can proceed with the login.', 'success')
        return redirect(url_for('users.login'))
    return render_template('users/reset_token.html', title='Reset Password',
                           form=form)

personal_blog/templates/users/account.html
{% extends "main/layout.html" %}
{% block content %}
    <div class="content-section">
        
        <div class="media">
            <img class="rounded-circle account-img" src="{{ profile_pic_path }}">
            <div class="media-body">
                <h2 class="account-heading">{{ current_user.username }}</h2>
                <p class="text-secondary">{{ current_user.email }}</p>
            </div>
        </div>

        <form method="POST" action="" enctype="multipart/form-data">
            {{ form.hidden_tag() }} <!-- CSRF token-->

            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Profile Info</legend>

                <div class="form-group">
                    {{ form.username.label(class="form-control-label") }}

                    {% if form.username.errors %}
                        {{ form.username(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.username(class="form-control form-control-lg") }}
                    {% endif %}
                </div>

                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}

                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>

                <div class="form-group">
                    {{ form.profile_pic.label() }}
                    {{ form.profile_pic(class="form-control-file") }}
                    {% if form.profile_pic.errors %}
                        {% for error in form.profile_pic.errors %}
                            <span class="text-danger">{{ error }}</span></br>
                        {% endfor %}
                    {% endif %}
                </div>

            </fieldset>

            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
                <button class="btn btn-warning">
                    <a href="{{ url_for('main.home') }}">Cancel</a>
                </button>
            </div>

            <div class="form-group">
                <hr>
                <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deactivateModal">
                    Deactivate account
                </button>
            </div>

        </form>

    </div>

<!-- Modal -->
<div class="modal fade" id="deactivateModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">

        <div class="modal-header">
          <h5 class="modal-title" id="deleteModalLabel">Deactivate account ?</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>

        <div class="modal-body">
          <p>Are you sure you want to deactivate your account ?</p>
          <p>This action is not reversible. 
          All your profile info, posts and comments will be permanently deleted.</p>
        </div>

        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
          <form action="{{ url_for('users.deactivate_account') }}" method="POST">
            <input class="btn btn-danger" type="submit" value="Deactivate">
          </form>
        </div>

      </div>
    </div>
  </div>

{% endblock content %}

personal_blog/templates/users/login.html
{% extends "main/layout.html" %}
{% block content %}

    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }} <!-- CSRF token-->
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Log In</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}

                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}

                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-check">
                    {{ form.remember(class="form-check-input") }}
                    {{ form.remember.label(class="form-check-label") }}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
                <small class="text-muted ml-2">
                    <a href="{{ url_for('users.reset_request') }}">Forgot your password ?</a>
                </small>
                <button class="btn btn-warning right">
                    <a href="{{ url_for('main.home') }}">Cancel</a>
                </button>
            </div>
        </form>
    </div>

    <div class="border-top pt-3">
        <small class="text-muted">
            Don't have an account ? <a class="ml-2" href="{{ url_for('users.register') }}">Register now</a>
        </small>
    </div>

{% endblock content %}

personal_blog/templates/users/register.html
{% extends "main/layout.html" %}
{% block content %}

    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }} <!-- CSRF token-->
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Join Now</legend>
                <div class="form-group">
                    {{ form.username.label(class="form-control-label") }}

                    {% if form.username.errors %}
                        {{ form.username(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.username(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}

                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}

                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.confirm_password.label(class="form-control-label") }}

                    {% if form.confirm_password.errors %}
                        {{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.confirm_password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.confirm_password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>

    <div class="border-top pt-3">
        <small class="text-muted">
            Do you already have an account ? <a class="ml-2" href="{{ url_for('users.login') }}">Log In</a>
        </small>
    </div>

{% endblock content %}

personal_blog/templates/users/reset_request.html
{% extends "main/layout.html" %}
{% block content %}

    <div class="content-section">
        <form method="POST" action="">

            {{ form.hidden_tag() }} <!-- CSRF token-->

            <fieldset class="form-group">

                <legend class="border-bottom mb-4">Reset password</legend>

                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}

                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>

            </fieldset>

            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
                <button class="btn btn-warning right">
                    <a href="{{ url_for('main.home') }}">Cancel</a>
                </button>
            </div>

        </form>
    </div>

{% endblock content %}

personal_blog/templates/users/reset_token.html
{% extends "main/layout.html" %}
{% block content %}

    <div class="content-section">
        <form method="POST" action="">

            {{ form.hidden_tag() }} <!-- CSRF token-->

            <fieldset class="form-group">

                <legend class="border-bottom mb-4">Reset password</legend>

                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}

                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>

                <div class="form-group">
                    {{ form.confirm_password.label(class="form-control-label") }}

                    {% if form.confirm_password.errors %}
                        {{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.confirm_password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.confirm_password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>

            </fieldset>

            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
                <button class="btn btn-warning right">
                    <a href="{{ url_for('main.home') }}">Cancel</a>
                </button>
            </div>

        </form>
    </div>

{% endblock content %}