personal_blog/books/routes.py
"""Module containing route functions for the books blueprint.

---

Functions
---------
add_book(): return http response
    the route for adding books
all_books(): return http response
    the route for displaying all books
book(book_id): return http response
    the route for displaying a single book
update_book(book_id): return http response
    the route for updating a book
delete_book(book_id): return http response
    the route for deleting a book
"""

from flask import Blueprint, render_template, url_for, flash, redirect, abort,\
        request
from flask_login import current_user, login_required

from personal_blog import db
from personal_blog.models import Book
from personal_blog.books.forms import BookForm

books = Blueprint('books', __name__)


@books.route("/book/new", methods=['GET', 'POST'])
@login_required
def add_book():
    """The route function for adding books.

    If the user isn't admin, don't do anything.
    If the form validates, add book to db.
    Flash the message, and redirect to all books.
    Else, just load the form (render the template).

    ---

    Returns
    -------
    http response
    """

    if not current_user.is_admin:  # only the admin adds books
        abort(403)
    form = BookForm()
    if form.validate_on_submit():
        book = Book(title=form.title.data, authors=form.authors.data,
                    link=form.link.data, edition=form.edition.data,
                    description=form.description.data)
        db.session.add(book)
        db.session.commit()
        flash('Book has been added!', 'success')
        return redirect(url_for('books.all_books'))
    return render_template('books/add_book.html', title='New Book',
                           form=form, legend='Add Book', hide_sidebar=True)


@books.route("/all_books")
def all_books():
    """The route function for displaying all books.

    Get all the records from the books table.
    Render the template.

    ---

    Returns
    -------
    http response
    """

    books = Book.query.all()
    return render_template('books/all_books.html', books=books)


@books.route("/book/<int:book_id>")
def book(book_id):
    """The route for displaying a single book.

    Query the books table for the record with that book id.
    Render the template.

    ----

    Parameters
    ----------
    book_id: int
        the id for the book to be displayed

    Returns
    -------
    http response
    """

    book = Book.query.get_or_404(book_id)
    return render_template('books/book.html', title=book.title, book=book)


@books.route("/book/<int:book_id>/update", methods=['GET', 'POST'])
@login_required
def update_book(book_id):
    """The route for updating a book.

    Get the book with that id, or return a 404.
    If the user isn't admin, don't do anything.
    If the form validates, apply changes to db.
    Flash the message, and redirect to that book's route.
    Else, render the template with the loaded record.

    ---

    Parameters
    ----------
    book_id: int
        the id of the book to be updated

    Returns
    -------
    http response
    """

    book = Book.query.get_or_404(book_id)
    if not current_user.is_admin:  # only the admin can update books
        abort(403)  # forbidden route
    form = BookForm()
    form.submit.label.text = 'Update'
    if form.validate_on_submit():
        book.title = form.title.data
        book.authors = form.authors.data
        book.edition = form.edition.data
        if form.link.data:
            book.link = form.link.data
        book.description = form.description.data
        db.session.commit()
        flash('Book has been updated!', 'success')
        return redirect(url_for('books.book', book_id=book.id))
    elif request.method == 'GET':
        form.title.data = book.title
        form.authors.data = book.authors
        form.edition.data = book.edition
        form.link.data = book.link
        form.description.data = book.description
    return render_template('books/add_book.html', title='Update Book',
                           form=form, legend='Update Book', hide_sidebar=True)


@books.route("/book/<int:book_id>/delete", methods=['POST'])
@login_required
def delete_book(book_id):
    """The route for deleting a book.

    Get the book with that id, or return a 404.
    If the user isn't admin, don't do anything.
    Delete the book from the db.
    Flash the message, and redirect to all books.

    ---

    Parameters
    ----------
    book_id: int
        the id of the book to be deleted

    Returns
    -------
    http response
    """

    book = Book.query.get_or_404(book_id)
    if not current_user.is_admin:
        abort(403)  # forbidden route
    db.session.delete(book)
    db.session.commit()
    flash('Book has been deleted!', 'success')
    return redirect(url_for('books.all_books'))

personal_blog/main/__init__.py
import personal_blog.main.utilities  # noqa: F401

personal_blog/main/routes.py
"""Module containing route functions for the main blueprint.

---

Functions
---------
landing_page(): return http response
    the route for the landing page
home(): return http response
    the route for the homepage
about(): return http response
    the route for the about page
search(): return http response
    the route for the search results
"""

from flask import Blueprint, request, render_template, g, redirect, url_for,\
        abort, current_app

from personal_blog.models import Post

main = Blueprint('main', __name__)


@main.route("/")
def landing_page():
    """The route function for the landing page.

    ---

    Returns
    -------
    http response
    """

    return render_template('main/landing_page.html')


@main.route("/home")
def home():
    """The route function for the homepage.

    Display all posts, paginated, from newest to oldest.

    ---

    Returns
    -------
    http response
    """

    page = request.args.get('page', 1, type=int)
    posts = Post.query.order_by(Post.date_posted.desc()).paginate(
        page=page, per_page=current_app.config['PER_PAGE_HOME'])
    return render_template('main/home.html', posts=posts)


@main.route("/about")
def about():
    """The route function for the about page.

    ---

    Returns
    -------
    http response
    """

    return render_template('main/about.html', title='About')


@main.route("/search")
def search():
    """The route function for the search results page.

    If the search text field is empty, redirect to homepage.
    Get matching posts, paginated, sorted by relevance.
    If the total is -1, elastic isn't running, so return code 500.
    If the total is 0, render the template with the display
    message of no matching results found.
    Else, calculate the next and previous links for the pagination.
    And render the template with the search results.

    ---

    Returns
    -------
    http response
    """

    if not g.search_form.validate():
        return redirect(url_for('main.home'))
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['PER_PAGE_GLOBAL']
    posts, total = Post.search(g.search_form.q.data, page, per_page)
    if total == -1:
        abort(500)
    elif total == 0:
        return render_template('main/search.html', title='Search',
                               results=False)
    next_url = url_for('main.search', q=g.search_form.q.data, page=page + 1) \
        if total > page * per_page else None
    prev_url = url_for('main.search', q=g.search_form.q.data, page=page - 1) \
        if page > 1 else None
    return render_template('main/search.html', title='Search', posts=posts,
                           next_url=next_url, prev_url=prev_url, results=True)

personal_blog/posts/routes.py
"""Module containing the route functions for the posts blueprint.

---

Functions
---------
new_post(): return http response
    the route for creating a new post
post(post_id): return http response
    the route for displaying a post with that id
update_post(post_id): return http response
    the route for updating a post with that id
delete_post(post_id): return http response
    the route for deleting a post with that id
all_posts(): return http response
    the route for displaying all posts
comment(post_id): return http response
    the route for adding a comment to that post
posts_by_tag(tag_content): return http response
    the route for displaying all posts with that tag
tags(): return http response
    the route for displaying all posts, grouped by tag
uploaded_files(filename): return http response, file url
    the route for getting the static file with that filename
upload(): return http response, file url
    the route for uploading a file (post image)
"""

import os
from secrets import token_hex

from flask import Blueprint, render_template, url_for, flash, redirect,\
    request, abort, send_from_directory, current_app
from flask_login import current_user, login_required
from flask_ckeditor import upload_fail, upload_success

from personal_blog import db
from personal_blog.models import Post, Tag, Comment
from personal_blog.posts.forms import PostForm, CommentForm
from personal_blog.posts.utilities import delete_post_images

posts = Blueprint('posts', __name__)


@posts.route("/post/new", methods=['GET', 'POST'])
@login_required
def new_post():
    """The route for creating a new post.

    If the current user isn't admin, early return code 403.
    If the form validates, create post and tag records.
    Flash the message, and redirect home.
    If it doesn't validate, simply render the template.

    ---

    Returns
    -------
    http response
    """

    if not current_user.is_admin:  # only the admin creates posts
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        post = Post(title=form.title.data, content=form.content.data,
                    author=current_user)
        db.session.add(post)
        # add tags
        tags = form.tags.data
        tags = set(tags.split(' '))
        parent_post = Post.query.order_by(Post.date_posted.desc()).first()
        for tag_name in tags:
            tag = Tag(content=tag_name, parent_post=parent_post)
            db.session.add(tag)
        # commit to db
        db.session.commit()
        flash('Post has been created!', 'success')
        return redirect(url_for('main.home'))
    return render_template('posts/create_post.html', title='New Post',
                           form=form, legend='Create Post', hide_sidebar=True)


@posts.route("/post/<int:post_id>")
def post(post_id):
    """The route function for displaying a post with that id.

    Get the post with that id, or return a 404.
    Get the comments for the post, ordered by date posted.
    Get the tags for the post. Render the template.

    ---

    Parameters
    ----------
    post_id: int
        the id of the post to be displayed

    Returns
    -------
    http response
    """

    post = Post.query.get_or_404(post_id)
    comments = Comment.query.filter_by(post_id=post_id).order_by(
            Comment.date_posted.asc())
    tags = Tag.query.filter_by(post_id=post_id)
    return render_template('posts/post.html', title=post.title, post=post,
                           comments=comments, tags=tags)


@posts.route("/post/<int:post_id>/update", methods=['GET', 'POST'])
@login_required
def update_post(post_id):
    """The route function for updating the post with that id.

    Get the post with that id, or return a 404.
    If the current user isn't the post author, return a 403.
    If the form validates, update the post record, delete the
    old tag records and create new ones, and then commit to db.
    Flash the message, and redirect to that post's route.
    If the form doesn't validate, or the request is GET,
    simply render the template.

    ---

    Parameters
    ----------
    post_id: int
        the id of the post to be updated

    Returns
    -------
    http response
    """

    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)  # forbidden route
    form = PostForm()
    form.submit.label.text = 'Update'
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        old_tags = Tag.query.filter_by(post_id=post_id)
        for tag in old_tags:
            db.session.delete(tag)
        new_tags = form.tags.data
        new_tags = set(new_tags.split(' '))
        for i in new_tags:
            tag = Tag(content=i, parent_post=post)
            db.session.add(tag)
        db.session.commit()
        flash('Your post has been updated!', 'success')
        return redirect(url_for('posts.post', post_id=post.id))
    elif request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.content
        tags = [tag.content for tag in post.tags]
        form.tags.data = ' '.join(tags)
    return render_template('posts/create_post.html', title='Update Post',
                           form=form, legend='Update Post', hide_sidebar=True)


@posts.route("/post/<int:post_id>/delete", methods=['POST'])
@login_required
def delete_post(post_id):
    """The route function for deleting the post with that id.

    Get the post with that id, or return a 404.
    If the current user isn't the post author, return a 403.
    Delete the post record, and commit to db.
    Delete the image files associated with that post.
    Flash the message, and redirect home.

    ---

    Parameters
    ----------
    post_id: int
        the id of the post to be deleted

    Returns
    -------
    http response
    """

    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)  # forbidden route
    content = post.content
    db.session.delete(post)
    db.session.commit()
    delete_post_images(content, current_app.root_path)
    flash('Your post has been deleted!', 'success')
    return redirect(url_for('main.home'))


@posts.route("/all_posts")
def all_posts():
    """The route function for displaying all posts.

    Get current page from the request object.
    Get all posts, ordered by date, and paginated.
    Render the template for the current page.

    ---

    Returns
    -------
    http response
    """

    page = request.args.get('page', 1, type=int)
    posts = Post.query.order_by(Post.date_posted.desc()).paginate(
        page=page, per_page=current_app.config['PER_PAGE_GLOBAL'])
    return render_template('posts/all_posts.html', posts=posts)


@posts.route("/post/<int:post_id>/comment", methods=['GET', 'POST'])
@login_required
def comment(post_id):
    """The route function for adding a comment to that post.

    Get the post with that id, or return a 404.
    If the form validates, create a comment record and commit it.
    Flash the message, and redirect to the post.
    If it doesn't validate, simply render the template.

    ---

    Parameters
    ----------
    post_id: int
        the id of the post to be commented on

    Returns
    -------
    http response
    """

    post = Post.query.get_or_404(post_id)
    form = CommentForm()
    if form.validate_on_submit():
        comment = Comment(content=form.content.data, user_id=current_user.id,
                          post_id=post.id)
        db.session.add(comment)
        db.session.commit()
        flash('Comment has been posted!', 'success')
        return redirect(url_for('posts.post', post_id=post.id))
    return render_template('posts/comment.html', title='Comment', form=form,
                           post=post, hide_sidebar=True)


@posts.route("/all_posts/<string:tag_content>")
def posts_by_tag(tag_content):
    """The route function for displaying all posts with that tag.

    Collect all the tag records with that tag content.
    Get the corresponding post id for each tag record collected.
    Get the current page from the request object.
    Get all the posts with those post ids, ordered by date
    posted, and paginated.
    Render the template.

    ---

    Parameters
    ----------
    tag_content: str
        the tag whole posts are to be displayed (i.e. 'django')

    Returns
    -------
    http response
    """

    tags = Tag.query.filter_by(content=tag_content).all()
    post_ids = [tag.post_id for tag in tags]
    page = request.args.get('page', 1, type=int)
    posts = db.session.query(Post).filter(Post.id.in_(post_ids)).order_by(
            Post.date_posted.desc()).paginate(
                page=page, per_page=current_app.config['PER_PAGE_GLOBAL'])
    return render_template('posts/posts_by_tag.html', posts=posts,
                           tag=tag_content)


@posts.route("/tags")
def tags():
    """The route function for displaying all posts, grouped by tag.

    Get all distinct tags. Render the template.

    ---

    Returns
    -------
    http response
    """

    tags = db.session.query(Tag.content.distinct().label("content")).all()
    return render_template('posts/tags.html', Tag=Tag, Post=Post, db=db,
                           tags=tags)


@posts.route('/files/<string:filename>')
def uploaded_files(filename):
    """The route function used by Ckeditor for getting uploaded files.

    Get the app path. Pass it on, along with the name
    of the requested file, to send_from_directory().
    Return the output of send_from_directory().

    ---

    Parameters
    ----------
    filename: str
        the name of the file to be retrieved

    Returns
    -------
    http response, filename url
    """

    path = current_app.config['UPLOADED_PATH']
    return send_from_directory(path, filename)


@posts.route('/upload', methods=['POST'])
def upload():

personal_blog/templates/main/_flashed_messages.html
{% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
        {% for category, message in messages %}
        <div class="alert alert-{{ category }}">
            {{ message }}
        </div>
        {% endfor %}
    {% endif %}
{% endwith %}

personal_blog/templates/main/_navigation_bar.html
<header class="site-header">
	<nav class="navbar navbar-expand-md navbar-dark bg-fblue fixed-top">
		<div class="container">

			<a class="navbar-brand mr-4" href="{{ url_for('main.home') }}">Julian's Blog</a>
			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle"
				aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
			</button>

			<div class="collapse navbar-collapse" id="navbarToggle">
				<div class="navbar-nav mr-auto">
					<a class="nav-item nav-link" href="{{ url_for('main.home') }}">Home</a>
					<div class="dropdown">
						<a href="javascript:void(0)" class="nav-item nav-link dropbtn">Posts</a>
						<div class="dropdown-content">
							<a class="nav-item nav-link" href="{{ url_for('posts.all_posts') }}">All Posts</a>
							<a class="nav-item nav-link" href="{{ url_for('posts.tags') }}">Posts by Tag</a>
						</div>
					</div>
					<a class="nav-item nav-link" href="{{ url_for('books.all_books') }}">Books</>
					<a class="nav-item nav-link" href="{{ url_for('main.about') }}">About</a>
				</div>

				<!-- Navbar Right Side -->
				<div class="navbar-nav">

					{% if g.search_form %}
					<form class="navbar-form navbar-left" method="get"
						  action="{{ url_for('main.search') }}">
						<div class="form-group mb-0 mt-1 input-group-sm">
							{{ g.search_form.q(size=20, class='form-control',
								placeholder=g.search_form.q.label.text) }}
						</div>
					</form>
					{% endif %}

					{% if current_user.is_authenticated %}
						{% if current_user.is_admin  %} 
						<!-- show the New Post and Add Book option only when it's me who is logged in -->
							<a class="nav-item nav-link" href="{{ url_for('posts.new_post') }}">New post</a>
							<a class="nav-item nav-link" href="{{ url_for('books.add_book') }}">Add Book</a>
						{% endif %}
						<a class="nav-item nav-link" href="{{ url_for('users.account') }}">Profile</a>
						<a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Log Out</a>
					{% else %}
						<a class="nav-item nav-link" href="{{ url_for('users.login') }}">Log In</a>
						<a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>
					{% endif %}
				</div>

			</div>
		</div>
	</nav>
</header>

personal_blog/templates/main/_sidebar.html
{% if not hide_sidebar %}
  <div class="col-md-4">
    <div class="content-section">

        <ul class="list-group">

            <li class="text-center mt-2">Welcome !</li>
            <div class="sidebar-section">
                <br>
                <p class="sidebar-paragraph">Hi, my name is Julian Hysi and I'm a Software Engineer.</p>
                <p class="sidebar-paragraph">I've built this blog to share my thoughts.</p>
                <p class="sidebar-paragraph">Hope you have a nice stay! </p>
                <br>
            </div>

            &emsp;

            {% if sidebar_posts %}
            <li class="text-center">Latest Posts</li>
                <div class="sidebar-section">
                    <ul>
                        <br>
                        {% for post in sidebar_posts %}
                            <li><p>- <a href="{{ url_for('posts.post', post_id=post.id)}}">
                                        {{post.title}}</a></p></li>
                        {%endfor%}
                        <br>
                    </ul>
                </div>
            {% endif %}
            
            &emsp;

            <li class="text-center">Contact</li>
            <div class="sidebar-section">
                <ul>
                  <br>
                  <li><p>Twitter: <a class="right mr-3" href="https://twitter.com/JulianHysi">
                                   @JulianHysi</a></p></li>
                  <li><p>GitHub: <a class="right mr-3" href="https://github.com/JulianHysi">
                                  @JulianHysi</a></p></li>
                  <li><p>LinkedIn: <a class="right mr-3" href="https://linkedin.com/in/julian-hysi">
                                    @julian-hysi</a></p></li>
                  <li><p>Email: <span class="right mr-3">julian_hysi@yahoo.com</span></p></li>
                  <li><p>Email: <span class="right mr-3">julian_hysi@live.com</span><p></li>
                  <br>
                </ul>
            </div>

        </ul>

    </div>
  </div>
{% endif %}

personal_blog/templates/main/about.html
{% extends "main/layout.html" %}
{% block content %}

<article class="content-section">
    <p>Personal blog site built with Python, Flask, HTML5 and Boostrap</p>
    <p>Deployed on March 2021</p>
    <p>For more details on how I built it, see <a href="#"><b>this</b></a> blog post</p>
    <p>To get in touch with me, see the <b>Contact</b> section on the sidebar</p>
    <p>The entire source code is available <a href="https://github.com/JulianHysi/personal_blog"><b>here</b></a><br>
    Feel free to clone it for your own needs, or fork and contribute to it</p>
</article>

{% endblock content %}

personal_blog/templates/main/home.html
{% extends "main/layout.html" %}
{% block content %}

    {% include "posts/_posts_overview.html" %}

    {% if posts.has_next or posts.has_prev %}  <!-- don't show pagination if there's just one page -->
        {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
            {% if page_num %}
                {% if posts.page == page_num %}
                    <a class="btn btn-info mb-4" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
                {% else %}
                    <a class="btn btn-outline-info mb-4" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
                {% endif %}
            {% else %}    
                ...
            {% endif %}
        {% endfor %}
    {% endif %}

{% endblock content %}

personal_blog/templates/main/landing_page.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <!-- CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/landing_page.css') }}">

    <link rel="icon" href="{{ url_for('static', filename='misc_images/favicon.png') }}">

    <title>Julian's Blog</title>
</head>

<body>

    <header id="showcase">
        <h1>Hi, my name is Julian Hysi and I'm a Software Engineer.</h1>
        <p>
            Welcome to my blog, where I share my 2 cents on programming and technology.<br>
            Click the button to proceed, or scroll down for a brief description of me.
        </p>
        <a href="{{ url_for('main.home') }}" class="button">Continue</a>
    </header>

	<section class="section section-light">
		<h2>About Me</h2>
		<p class="pt-4">
            I am a Software Engineer currently based in Tirana, Albania. I have graduated in Software Engineering and 
            I have been working full-time as one, since prior to my graduation.<br>
            Most of my work revolves around back-end development, working with databases and writing standalone scripts to 
	    automate tasks.<br>
            I worked at 2 companies for 4 years before switching to full-time freelancing.
        </p>
        <p class="mt-4">
            Proceed to the blog and on the sidebar you'll find my contact info.
		</p>
	</section>

	<section class="section section-dark">
		<h2>Tech Stack</h2>
		<p class="pt-4">
            My tech belt includes Python, Java, X++, SQL, Flask, Django, pandas, matplotlib, HTML, Bootstrap, Linux, bash, git, vim,
            nginx, Docker, CircleCI, TFVC, ERP, SQLite, Microsoft SQL Server, PostgreSQL etc.
		</p>
	</section>

	<div class="pimg2">
	</div>

	<section class="section section-dark">
	    <h2>My Modus Operandi</h2>
		<p class="pt-4">
            My code incorporates the OOP paradigm, design patterns, SOLID principles, algorithm complexity, language/framework best
            practices, documentation, testing, clean code and refactoring, and security measures.
        </p>
	</section>

	<section class="section section-light">
		<h2>Experiences</h2>
		<p class="pt-4">
            I have experience with DevOps, SCRUM and issue tracking systems, backups, deploying and servers, code and database
            migrations, technical consultancy, functional requirements writing, large codebases, large teams, hands-on client meetings,
            talks and presentations, remote work/assistance, junior mentorship, CI/CD, database design and normalization etc.
		</p>
	</section>

    <div class="pimg3">
	</div>

    <section class="section section-light">
        <h2>Looking to learn</h2>
        <p class="pt-4">
            I'm a tech enthusiast always looking for something to learn/practice. Right now hot on my list are Machine Learning,
            TDD, FastAPI, some Javascript framework (React or Vue), functional programming (Clojure), XP, competitive programming.
        </p>
    </section>

    <section class="section section-dark">
        <h2>Hobbies</h2>
        <p class="pt-4">
            Outside the world of programming and computers, I enjoy walking and exploring nature, riding the bicycle, eating healthy,
            reading science and fiction, living a minimalist life, teaching others what I know, learning and 
            continuous self-improvement and spending time with my family.
        </p>
    </section>

</body>

</html>

personal_blog/templates/main/search.html
{% extends "main/layout.html" %}

{% block content %}

    <h2>Search Results :</h2>

    {% if not results %}
        <h4 class="text-muted mt-5">No matching result found..</h4>
    {% else %}

        {% for post in posts %}
            <article class="media content-section">
                <a href="{{ url_for('posts.all_posts') }}">
                    <img class="rounded-circle article-img"
                         src="{{ url_for('static', filename='profile_pics/' + post.author.profile_pic) }}">
                </a>
                <div class="media-body">
                    <div class="article-metadata">
                        <a class="mr-2" href="{{ url_for('posts.all_posts') }}">{{ post.author.username }}</a>
                        <small class="text-muted right"> {{ post.date_posted.strftime('%-d %B, %Y') }} </small>
                    </div> <br>
                    <h2><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
                </div>
            </article>
        {% endfor %}

        {% if prev_url or next_url %}  <!-- don't show pagination if there's just one page -->
        <nav aria-label="...">
            <div class="text-center">
            {% if prev_url %}
                <a class="btn btn-outline-info mb-4" href="{{ prev_url }}">
                    <span aria-hidden="true">&larr;</span>Prev
                </a>
            {% else %} 
                <a class="btn btn-outline-info mb-4 disabled" href="#">
                    <span aria-hidden="true">&larr;</span>Prev
                </a>
            {% endif %}
            
            {% if next_url %}
                <a class="btn btn-outline-info mb-4" href="{{ next_url }}">
                    Next<span aria-hidden="true">&rarr;</span>
                </a>
            {%  else %}
                <a class="btn btn-outline-info mb-4 disabled" href="#">
                    Next<span aria-hidden="true">&rarr;</span>
                </a>
            {% endif %}
            </div>
        </nav>
        {% endif %}

    {% endif %}

{% endblock %}